### PR TITLE
Fixed error in convert Ventilation.cs

### LINKED ISSUE #42: Error in convert Ventilation.cs
#### Description:

When converting the SAP Ventilation Object to a XML Ventilation object an error occurs in the convert when not all inputs are there. The issue will be solved adding an if loop so the convert accepts null properties.

### PR DESCRIPTION
**Pull request by emilsvedjer**
### Issues addressed by this PR

Closes #42 

### Additional comments

Fixed error in ventilation convert from SAP object to XML object. Before it gave an error when not all ventilation objects were input (which causes a problem since you don't have to provide all possible inputs in all cases)

### CODE REVIEW

File: SAP_Engine/Convert/Ventilation.cs [hunk 1]
```diff
@@ -38,26 +38,81 @@ public static partial class Convert
...
             BH.oM.Environment.SAP.XML.Ventilation xmlVentilation = new BH.oM.Environment.SAP.XML.Ventilation();
+            if (sapVentilation.VentilationRates == null)
+            {
+                xmlVentilation.numOpenFireplaces = null;
+                xmlVentilation.numOpenFlues = null;
+                xmlVentilation.numFluelessGasFires = null;
+                xmlVentilation.ExtractFansCount = null;
+                xmlVentilation.PSVCount = null;
+            }
+
```
Comment (FraserGreenroyd) [inline SAP_Engine/Convert/Ventilation.cs:49]:
```suggestion
```

File: SAP_Engine/Convert/Ventilation.cs [hunk 2]
```diff
@@ -38,26 +38,81 @@ public static partial class Convert
...
+                xmlVentilation.ExtractFansCount = sapVentilation.VentilationRates.FansCount;
+                xmlVentilation.PSVCount = sapVentilation.VentilationRates.PSVCount;
+            }
+
+            if (sapVentilation.AirPermability == null)
+            {
+                xmlVentilation.PressureTest = null;
+                xmlVentilation.AirPermability = null;
+            }
+
```
Comment (FraserGreenroyd) [inline SAP_Engine/Convert/Ventilation.cs:64]:
```suggestion
```

File: SAP_Engine/Convert/Ventilation.cs [hunk 3]
```diff
@@ -38,26 +38,81 @@ public static partial class Convert
...
+                xmlVentilation.IsMechanicalVentApprovedInstallerScheme = sapVentilation.VentilationStrategy.ApprovedInstallation;
+                xmlVentilation.MechanicalVentDuctsIndexNumber = sapVentilation.VentilationStrategy.MechVentSystemIndexNumber;
+                if (sapVentilation.VentilationStrategy.MechVentDetails == null)
+                {
+                    xmlVentilation.MechanicalVentSystemMakeModel = null;
+                    xmlVentilation.MechanicalVentSpecificFanPower = null;
+                    xmlVentilation.MechanicalVentHeatRecoveryEfficiency = null;
+                    xmlVentilation.MechanicalVentDuctType = null;
+                }
+
```
Comment (FraserGreenroyd) [inline SAP_Engine/Convert/Ventilation.cs:105]:
```suggestion
```

File: SAP_oM/Ventilation.cs [hunk 4]
```diff
@@ -32,16 +32,16 @@ namespace BH.oM.Environment.SAP
     public class Ventilation : BHoMObject
     {
         [Description("The number of sheltered sides in the Property. Min/max 0/4.")]
-        public virtual string numShelteredSides { get; set; } = "0";
+        public virtual string numShelteredSides { get; set; } = null;
```
Comment (FraserGreenroyd) [inline SAP_oM/Ventilation.cs:35]: This should be `NumberOfShelteredSides` for completeness - but can be handled in a future PR.

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

**Review by FraserGreenroyd — APPROVED** [review]
Review of code looks fine to me, merging to allow easier review by @rboulton-BH when back from leave.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance
